### ISSUE TITLE
Posible problema en archivo de configuración

### ISSUE THREAD

**Issue by biaggi** [cellsjs/piscosour#24]
Tengo un archivo de configuración que me está dando un problema y por más que lo miro, no veo que sea json inválido:

Este es el archivo: (shots/init/app/params.json)
{
  "repository": "https://descinet.bbva.es/stash/scm/bbvacellsapp/mobilebanking.es.git",
  "branch": "develop",
  "prefix": "bamboo",
  "task": "dist:vulcanize"
}

Este es el error:

bin/pisco.js app:prepare
[12:19:40] Your repository type is: [ app ]
[12:19:40] Sipping straw [ app:prepare ] shots: [ 'init' ]
Trace: [TypeError: Cannot read property 'repository' of undefined]
    at /home/jmgomez/cells/piscosour/lib/sour.js:75:25
    at Object.gush (/home/jmgomez/cells/piscosour/lib/sour.js:35:23)
    at Object.Piscosour.gush (/home/jmgomez/cells/piscosour/index.js:23:21)
    at Object.<anonymous> (/home/jmgomez/cells/cells-pisco-application-deploy/.tmp/bin/pisco.js:2:22)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)

Este es el código: 

https://descinet.bbva.es/stash/projects/CELLSLABS/repos/cells-pisco-application-deploy/browse?at=refs%2Fheads%2Ffeature%2Fprepare

Saludos

**Comment by sbonacho** [comment]
He conseguido repetir este error... se trata de un error.

**Comment by biaggi** [comment]
No me ha quedado clara esa respuesta, es algo de la receta? o del core de pisco

**Comment by sbonacho** [comment]
Es del core de pisco.

**Comment by sbonacho** [comment]
Debería estar corregido por el pull request que acabo de mandar.

**Comment by biaggi** [comment]
Está bien, llegan los parámetros, pero habría que pensar en cómo encapsular la parte de parámetros de consola de alguna forma que sea agnóstica al lector de parámetros que se esté usando. De esta forma si en algún momento, queremos cambiarlo, nadie habrá atado código a implementaciones concretas.

[09:11:08] Your repository type is: [ app ]
[09:11:08] Sipping straw [ app:prepare ] shots: [ 'init' ]
[09:11:08] Piscosour shot [ app:init ]
[09:11:08] 

 Acts as a constructor 

[09:11:08] run Run main execution
{ argv: 
   { remain: [ 'app:prepare' ],
     cooked: [ 'app:prepare' ],
     original: [ 'app:prepare' ] },
  repository: 'https://descinet.bbva.es/stash/scm/bbvacellsapp/mobilebanking.es.git',
  branch: 'develop',
  prefix: 'bamboo',
  task: 'dist:vulcanize' }
[09:11:08] Straw [ app:prepare ] sipped
[09:11:08] finalCheck...

Pero eso es otra historia y será tratada en otra issue

**Comment by sbonacho** [comment]
Actualmente los parámetros están encapsulados dentro de la librería
params.js y se recogen como parámetros clave:valor en shot.runner.params
podemos cambiar la implementación de params.js usando commander sin ningún
problema y manteniendo la funcionalidad.

Vamos, que actualmente no está atado a implementaciones concretas.
