### ISSUE TITLE
Curioso error, no me encuentra un shot.js

### ISSUE THREAD

**Issue by biaggi** [cellsjs/piscosour#4]
Algo debo estar haciendo mal, pero el log tampoco me da muchas pistas, adjunto ejemplo:

ls -la /home/jmgomez/cells/cells/cells/shots/create/component/shot.js
-rw-rw-r-- 1 jmgomez jmgomez 365 feb 12 11:56 /home/jmgomez/cells/cells/cells/shots/create/component/shot.js

[13:00:49] shooter:load /home/jmgomez/cells/cells/cells/shots/create/component/shot.js doesn't exist!

```
ls -la /home/jmgomez/cells/cells/cells/shots/create/component/shot.js && ../../cells/cells/bin/pisco.js component:environment
-rw-rw-r-- 1 jmgomez jmgomez 365 feb 12 11:56 /home/jmgomez/cells/cells/cells/shots/create/component/shot.js
/home/jmgomez/cells/components/cells-composer-ui-dialog-create
[13:00:49] Your repository type is: [ component ]
[13:00:49] Sipping straw [ component:environment ] shots: [ 'create', 'system', 'npm' ]
[13:00:49] Piscosour shot [ component:create ]
trace { piscosour: '/home/jmgomez/cells/cells/cells/node_modules/piscosour',
  module: '/home/jmgomez/cells/cells/cells',
  c_local: '/home/jmgomez/cells/components/cells-composer-ui-dialog-create/.piscosour' } { name: 'create',
  orig: 'component:create',
  repoType: 'component',
  params: { paramName1: 'value1', paramName2: [], paramName3: {} } }
[13:00:49] shooter:load /home/jmgomez/cells/cells/cells/node_modules/piscosour/shots/create/component/shot.js doesn't exist!
[13:00:49] shooter:load /home/jmgomez/cells/cells/cells/shots/create/component/shot.js doesn't exist!
Trace: [TypeError: Cannot read property 'description' of undefined]
    at /home/jmgomez/cells/piscosour/lib/sour.js:84:25
    at Object.gush (/home/jmgomez/cells/piscosour/lib/sour.js:27:23)
    at Object.<anonymous> (/home/jmgomez/cells/cells/cells/bin/pisco.js:13:6)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

**Comment by biaggi** [comment]
Misterio resuelto: 

{ [Error: Cannot find module 'cells-ci-pull-all'] code: 'MODULE_NOT_FOUND' }

Pero me gustaría que el error fuera más claro

**Comment by biaggi** [comment]
No tengo permisos para hacer un pull request en el repo, así es que adjunto diff en formato unified diff, se aplica con patch -p1 < file en el raiz del proyecto

Esta es mi proposición para este problema

```
diff --git a/lib/shooter.js b/lib/shooter.js
index 55a62c0..f5b2e71 100755
--- a/lib/shooter.js
+++ b/lib/shooter.js
@@ -83,17 +83,27 @@ var shooter = function(){
             if (!name.startsWith('c_')) {
                 var filename = path.join(config.modulesDir[name], "shots", normal.name, normal.repoType, "shot.js");
                 logger.trace("#green", "shooter:load", "trying", "[", name, "]", filename, "...");
+                var stat = null;
                 try {
-                    shot = config.merge(require(filename), shot);
-                    shot.runner.name = normal.name;
-                    shot.runner.params = normal.params;
-                } catch (e) {
+                    stat = fs.statSync(filename);
+                } catch(e) {
                     logger.trace("#red", "shooter:load", e);
                     if (e.code === 'MODULE_NOT_FOUND')
                         errors.push(["#red", "shooter:load", "#yellow", filename, "doesn't exist!"]);
                     else
                         logger.error("#red", "shooter:load", "#yellow", filename, e);
                 }
+
+                if (stat != null) {
+                    try {
+                        shot = config.merge(require(filename), shot);
+                        shot.runner.name = normal.name;
+                        shot.runner.params = normal.params;
+                    } catch (e) {
+                        logger.trace("#red", "shooter:load", e);
+                        logger.error("#red", "shooter:load", "#yellow", "Sintax error in the file", filename, e);
+                    }
+                }
             }
         }


```

Generará un error del tipo: 

[14:11:14] run Run main execution
[14:11:14] shooter:synchro stop at run ( 2 of 5 ) {}
[14:11:14] sipper:synchro Shot error stops the straw!! [ReferenceError: pullAll is not defined]
[14:11:14] Write results in junit format at test-reports/pisco-unit.xml

**Comment by sbonacho** [comment]
Efectivamente había observado este mal comportamiento. Me pongo con ello, me pongo en la rama que has abierto y reviso el pull request para comprobar si cumple todos los requisitos, Muchas gracias!!

**Comment by sbonacho** [comment]
solucionado! he hecho un merge de la feature 388b768338e7a2d31166d277d60530feb9b28ba4 a master... (pero creo que algo no he hecho bien...)
